[package]
name = "wgpu_mandelbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = {version = "0.29", features = ["rwh_05"]}
env_logger = "0.11.5"
log = "0.4"
wgpu = "22.0"